# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1092, 647)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter.setMaximumSize(QtCore.QSize(10005, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName("splitter")
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(5000, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsView_main = PlotWidget(self.widget_2)
        self.graphicsView_main.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsView_main.setObjectName("graphicsView_main")
        self.verticalLayout_6.addWidget(self.graphicsView_main)
        self.graphicsView_recovered = PlotWidget(self.widget_2)
        self.graphicsView_recovered.setObjectName("graphicsView_recovered")
        self.verticalLayout_6.addWidget(self.graphicsView_recovered)
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.slider_value = QtWidgets.QLabel(self.frame_2)
        self.slider_value.setText("")
        self.slider_value.setObjectName("slider_value")
        self.gridLayout_3.addWidget(self.slider_value, 0, 4, 1, 1)
        self.pushButton_recover = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_recover.setObjectName("pushButton_recover")
        self.gridLayout_3.addWidget(self.pushButton_recover, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 3, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_2)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(1500)
        self.horizontalSlider.setProperty("value", 500)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_3.addWidget(self.horizontalSlider, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 5, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.verticalLayout_6.addWidget(self.groupBox_7)
        self.verticalLayout_6.setStretch(0, 50)
        self.verticalLayout_6.setStretch(1, 30)
        self.verticalLayout_6.setStretch(2, 20)
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(5000, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.graphicsView_sum = PlotWidget(self.groupBox)
        self.graphicsView_sum.setEnabled(True)
        self.graphicsView_sum.setObjectName("graphicsView_sum")
        self.verticalLayout_5.addWidget(self.graphicsView_sum)
        self.Exporting_composed_button = QtWidgets.QPushButton(self.groupBox)
        self.Exporting_composed_button.setObjectName("Exporting_composed_button")
        self.verticalLayout_5.addWidget(self.Exporting_composed_button)
        self.add_to_composer_button = QtWidgets.QPushButton(self.groupBox)
        self.add_to_composer_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.add_to_composer_button.setObjectName("add_to_composer_button")
        self.verticalLayout_5.addWidget(self.add_to_composer_button)
        self.graphicsView_sine = PlotWidget(self.groupBox)
        self.graphicsView_sine.setObjectName("graphicsView_sine")
        self.verticalLayout_5.addWidget(self.graphicsView_sine)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 130))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame = QtWidgets.QFrame(self.groupBox_6)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.freq_label = QtWidgets.QLabel(self.frame)
        self.freq_label.setObjectName("freq_label")
        self.gridLayout_2.addWidget(self.freq_label, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.mag_label = QtWidgets.QLabel(self.frame)
        self.mag_label.setText("")
        self.mag_label.setObjectName("mag_label")
        self.gridLayout_2.addWidget(self.mag_label, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 5, 1, 1)
        self.phase_label = QtWidgets.QLabel(self.frame)
        self.phase_label.setText("")
        self.phase_label.setObjectName("phase_label")
        self.gridLayout_2.addWidget(self.phase_label, 0, 6, 1, 1)
        self.add_to_combobox = QtWidgets.QPushButton(self.frame)
        self.add_to_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.add_to_combobox.setObjectName("add_to_combobox")
        self.gridLayout_2.addWidget(self.add_to_combobox, 1, 0, 1, 1)
        self.freqency_slider = QtWidgets.QSlider(self.frame)
        self.freqency_slider.setOrientation(QtCore.Qt.Horizontal)
        self.freqency_slider.setObjectName("freqency_slider")
        self.gridLayout_2.addWidget(self.freqency_slider, 1, 1, 1, 2)
        self.magnitude_slider = QtWidgets.QSlider(self.frame)
        self.magnitude_slider.setOrientation(QtCore.Qt.Horizontal)
        self.magnitude_slider.setObjectName("magnitude_slider")
        self.gridLayout_2.addWidget(self.magnitude_slider, 1, 3, 1, 2)
        self.phase_slider = QtWidgets.QSlider(self.frame)
        self.phase_slider.setOrientation(QtCore.Qt.Horizontal)
        self.phase_slider.setObjectName("phase_slider")
        self.gridLayout_2.addWidget(self.phase_slider, 1, 5, 1, 2)
        self.verticalLayout_8.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.delete_from_combo = QtWidgets.QPushButton(self.frame_3)
        self.delete_from_combo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.delete_from_combo.setObjectName("delete_from_combo")
        self.horizontalLayout_3.addWidget(self.delete_from_combo)
        self.comboBox_subsignal = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_subsignal.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox_subsignal.setEditable(False)
        self.comboBox_subsignal.setObjectName("comboBox_subsignal")
        self.horizontalLayout_3.addWidget(self.comboBox_subsignal)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.verticalLayout_5.setStretch(0, 33)
        self.verticalLayout_5.setStretch(3, 33)
        self.verticalLayout_5.setStretch(4, 30)
        self.horizontalLayout.addWidget(self.splitter)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 50))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon)
        self.actionAdd.setObjectName("actionAdd")
        self.actionSample = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/sample.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSample.setIcon(icon1)
        self.actionSample.setObjectName("actionSample")
        self.actionClear = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/restart.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon2)
        self.actionClear.setObjectName("actionClear")
        self.actionPlot = QtWidgets.QAction(MainWindow)
        self.actionPlot.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/signal.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlot.setIcon(icon3)
        self.actionPlot.setObjectName("actionPlot")
        self.actionHide = QtWidgets.QAction(MainWindow)
        self.actionHide.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/hide.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHide.setIcon(icon4)
        self.actionHide.setObjectName("actionHide")
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPlot)
        self.toolBar.addAction(self.actionSample)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHide)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_7.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton_recover.setText(_translate("MainWindow", "Recover"))
        self.label.setText(_translate("MainWindow", "Sampling Frequency"))
        self.groupBox.setTitle(_translate("MainWindow", "Signal Composer"))
        self.Exporting_composed_button.setText(_translate("MainWindow", "PushButton"))
        self.add_to_composer_button.setText(_translate("MainWindow", "add▲ing"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_2.setText(_translate("MainWindow", "Frequency"))
        self.freq_label.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "Magnitude"))
        self.label_4.setText(_translate("MainWindow", "Phase-Shift"))
        self.add_to_combobox.setText(_translate("MainWindow", "add to combobox"))
        self.delete_from_combo.setText(_translate("MainWindow", "Delete"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionAdd.setToolTip(_translate("MainWindow", "Add a Signal"))
        self.actionSample.setText(_translate("MainWindow", "Sample"))
        self.actionSample.setToolTip(_translate("MainWindow", "Sample Signal"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear Graph"))
        self.actionPlot.setText(_translate("MainWindow", "Plot"))
        self.actionPlot.setToolTip(_translate("MainWindow", "Plot/Hide"))
        self.actionHide.setText(_translate("MainWindow", "Hide"))
        self.actionHide.setToolTip(_translate("MainWindow", "Hide Reconstruction Graph"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

